runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://heroku_s4cc7q21:ulvvbnqua7u59u551vbhpbmvjh@ds145194.mlab.com:45194/heroku_s4cc7q21
  APP_ID: 10
  MASTER_KEY: 1010
  SERVER_URL: https://parsejssample.herokuapp.com/parse
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  
